title: LambdaWorks Documentation
description: Documentation for LambdaWorks Unreal Engine plugins.
logo: "logo.png"
favicon_ico: "favicon.ico"

color_scheme: dark
theme: just-the-docs

url: https://lambda-w.github.io/Documentation/docs/index

aux_links:
  "GitHub":
    - "//github.com/Lambda-W/"
    
  "Fab":
    - "//www.fab.com/sellers/Lambda%20Works"
